mystruct.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include `mystruct.h`
Functions
struct Employee * makeEmployee (int birth, int start, const char *name)
void printEmployee (struct Employee *e)
struct Employee * makeRandomEmployee ()
int randint (int max)
char randChar ()
char * randStr (int size)
struct Employee ** makeArr (int count)
void printEmployeesArr (struct Employee **arr, int count)
struct Employee ** dupArr (struct Employee **arr, int count)
void deAlloc (struct Employee **arr, int count)
struct Employee ** dupArr1 (struct Employee **arr, int count)
Function Documentation
deAlloc()
void deAlloc (struct Employee ** arr, int count)
dupArr()
struct Employee** dupArr (struct Employee ** arr, int count)
Referenced by testDupArr().
dupArr1()
struct Employee** dupArr1 (struct Employee ** arr, int count)
References Employee::birth_year, makeEmployee(), Employee::name, and Employee::start_year.
Referenced by testDupArr1().
makeArr()
struct Employee** makeArr (int count)
References makeRandomEmployee().
Referenced by testDupArr(), testDupArr1(), testMakeArr(), and testPrintEmployeeArr().
makeEmployee()
struct Employee* makeEmployee (int birth, int start, const char * name)
mystruct.c
Author
Mike Ciaraldi Allocates an Employee struct and fills in its fields
Parameters
birth Year the employee was born.
start Year the employee started with the company.
name String containing employee's name
Returns
Pointer to Employee struct, newly allocated from the heap.
References Employee::birth_year, MAX_NAME, Employee::name, and Employee::start_year.
Referenced by dupArr1(), makeRandomEmployee(), and testMakeEmployee().
makeRandomEmployee()
struct Employee* makeRandomEmployee ()
References makeEmployee(), MAX_NAME, Employee::name, randint(), and randStr().
Referenced by makeArr(), and testMakeRandomEmployee().
printEmployee()
void printEmployee (struct Employee * e)
Prints the given employee
Parameters
struct Employee *e, the employee whose info is to be printed @ return void, just prints the details of the employee
References Employee::birth_year, Employee::name, and Employee::start_year.
Referenced by printEmployeesArr(), testMakeEmployee(), testMakeRandomEmployee(), and testPrintEmployee().
printEmployeesArr()
void printEmployeesArr (struct Employee ** arr, int count)
References printEmployee().
Referenced by testDupArr(), testDupArr1(), and testPrintEmployeeArr().
randChar()
char randChar ()
References randint().
Referenced by randStr(), and testRandChar().
randint()
int randint (int max)
Referenced by makeRandomEmployee(), randChar(), and testRandInt().
randStr()
char* randStr (int size)
References randChar().
Referenced by makeRandomEmployee(), and testRandStr().